<h1> Soal 1: Pemahaman Tentang Model Evaluasi</h1>

Jawab pertanyaan di bawah ini dengan bahasa masing-masing?

1. Apa perbedaan antara data latih, data validasi, dan data test?
2. Bagaimana cara kita menilai performa suatu model?
3. Apa itu Confusion Matrix? Jelaskan secara lengkap!
4. Apa itu Classification Report dari sklearn?

Jawab:
1. Data Latih: data yang digunakan untuk training model

  Data Validasi: digunakan untuk proses validasi model dan mencegah overfitting.

  Data Test: digunakan untuk testing model, sebagai simulasi penggunaan model pada dunia nyata. Data testing tidak boleh pernah dilihat oleh model sebelumnya.

2. kita jangan memakai data yg sama dengan data yg kita latih. kita harus memiliki data lain yg tidak kita latih kemudian kita jadikan data test. cara mendapatkan data testnya bisa dengan menggunakan function sklearn yaitu train_test_split yg fungsinya mensplit data kita menjadi data traning dan data testing

3. Confusion matrix juga sering disebut error matrix. Pada dasarnya confusion matrix memberikan informasi perbandingan hasil klasifikasi yang dilakukan oleh sistem (model) dengan hasil klasifikasi sebenarnya. Confusion matrix berbentuk tabel matriks yang menggambarkan kinerja model klasifikasi pada serangkaian data uji yang nilai sebenarnya diketahui. Terdapat 4 istilah sebagai representasi hasil proses klasifikasi pada confusion matrix. Keempat istilah tersebut adalah True Positive (TP), True Negative (TN), False Positive (FP) dan False Negative (FN).

4. untuk melakukan report dari hasil prediksi modelling. dimana reportnya berdasarkan confusion matrix (precision, recall, f1score). 

---

<h1>Soal 2: Aplikasi Model Evaluasi</h1>

Kali ini kita akan menggunakan data untuk memprediksi kelangsungan hidup pasien yang telah mengalami operasi payudara. Dengan informasi yang dimiliki terkait pasien, kita akan membuat model untuk memprediksi apakah pasien akan bertahan hidup dalam waktu lebih dari 5 tahun atau tidak.

Lebih Lengkapnya kalian bisa membaca informasi tentang dataset di link berikut: https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.names

Buat model Klasifikasi (Model/Algoritma Bebas) untuk memprediksi status pasien dengan ketentuan sebagai berikut:

1. Bagi kedua data ini menjadi data training dan data test dengan test_size=0.25.
3. Pelajar tentang metrics roc_auc_score kemudian buatlah model dan evaluasi dengan menggunakan teknik cross-validation dengan scoring 'roc_auc'. Baca https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html untuk menggunakan metric roc_auc saat cross-validation.
3. Berapa score rata2 dari model dengan teknik cross-validation tersebut?
4. Prediksi data test dengan model yang telah kalian buat!
5. Bagaimana hasil confusion matrix dari hasil prediksi tersebut?
6. Bagaimana classification report dari hasil prediksi tersebut?
5. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status positive?
6. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status negatif?

In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [ ]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [ ]:
df['survival_status'].value_counts()

1    225
2     81
Name: survival_status, dtype: int64

In [ ]:
# Code here
#import class algorithm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

#splitting data feature and data target
x = df.drop('survival_status', axis=1)
y = df['survival_status']

#Bagi kedua data menjadi data training dan data test dengan test_size=0.25.
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=21, stratify=y)

In [ ]:
print(x.shape, x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(306, 3) (229, 3) (77, 3) (229,) (77,)


In [ ]:
#membuat objek model
model_knn = KNeighborsClassifier(n_neighbors=2)
model_knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')

In [ ]:
from sklearn.model_selection import cross_val_score

#model dan evaluasi dengan menggunakan teknik cross-validation dengan scoring 'roc_auc'
model_knn = KNeighborsClassifier(n_neighbors=2)
cv_result = cross_val_score(model_knn, x, y, cv=5, scoring='roc_auc')
cv_result

array([0.65555556, 0.54166667, 0.61041667, 0.63194444, 0.63888889])

In [ ]:
#rata-rata dari model dengan teknik cross-validation
cv_result.mean()

0.6156944444444444

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

#confusion_matrix dari hasil prediksi
confusion_matrix(y_test, y_predik)

array([[50,  7],
       [14,  6]])

In [ ]:
#classification report dari hasil prediksi
print(classification_report(y_test, y_predik))

              precision    recall  f1-score   support

           1       0.78      0.88      0.83        57
           2       0.46      0.30      0.36        20

    accuracy                           0.73        77
   macro avg       0.62      0.59      0.60        77
weighted avg       0.70      0.73      0.71        77



In [ ]:
TP = 50
FN = 7
FP = 14
TN = 6

#Seberapa baik model dalam memprediksi seorang pasien mempunyai status positive
precision = TP/(TP+FP)
print('precision', precision)
print('='*50)

recall = TP/(TP+FN)
print('recall' ,recall)
print('='*50)

f1score = 2*precision*recall/(precision + recall)
print('f1score' ,f1score)
print('='*50)

precision 0.78125
recall 0.8771929824561403
f1score 0.8264462809917354


In [ ]:
#Seberapa baik model dalam memprediksi seorang pasien mempunyai status negative
precision = TN/(TN+FN)
print('precision', precision)
print('='*50)

recall = TN/(TN+FP)
print('recall' ,recall)
print('='*50)

f1score = (precision*recall*2)/(precision+recall)
print('f1score' ,f1score)
print('='*50)

precision 0.46153846153846156
recall 0.3
f1score 0.3636363636363637


---

<h1> Soal 3: Pemahaman Tentang Model Selection</h1>

Jelaskan dengan bahasa sendiri!

1. Apa itu Bias dan Variance?
2. Apa itu Overfitting dan Underfitting?
3. Apa yang bisa kita lakukan untuk mengatur kompleksitas dari model?
4. Bagaimana model yang baik?
5. Kapan kita menggunakan GridSearchcv dan kapan menggunakan RandomizedSearchCV?

Jawab:

1. Bias = error yang disebabkan oleh suatu perbedaan hasil prediksi dengan nilai sebenarnya (modelnya terlalu simple). Variance = Model yang terlalu attention terhadap data training dan tidak bisa mengeneralisir terhadap data yang belum mereka lihat (modelnya terlalu kompleks)

2. Overfitting = suatu keadaan dimana suatu data itu terlalu belajar terhadap data training sehingga terlalu menangkap detail dan noise. Underfitting = suatu keadaan dimana modelnya buruk ketika belajar dalam data training

3.  dengan cara mencari nilai tengah/trade off dari sebuah model

4. model yang baik adalah model yang memiliki error bias dan variance yang kecil

5. GridSearchCV digunakan ketika kita ingin melakukan semua kombinasi hyperparameter. RandomizedSearchCV digunakan untuk melakukan beberapa kombinasi parameter saja

---

<h1> Soal 4: Aplikasi Model Selection</h1>

1. Bagi kedua data berikut ini menjadi data training dan data test dengan test_size=0.25.
2. Gunakan algoritma KNN sebagai model classifier.
3. Gunakan fungsi GridSearchCV untuk hyperparameter tuning dan model selection.
4. jumlah fold bebas!, gunakan scoring 'roc_auc'
5. Definisikan kombinasi hyperparameter untuk model selection dengan GridSearchCV. kombinasi Hyperparameter bebas, baca lagi dokumentasi KNN di link berikut https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html untuk memahami lagi jenis2 hyperparameter di algorithma KNN.
6. Latih model terhadap data training.
7. Apa hyperparameter terbaik untuk kombinasi hyperparameter kalian?
8. Berapa score validasi terbaik dari model tersebut?
9. Prediksi probabilitasi output dari model yang telah di buat terhadap data test. note : gunakan method .predict_proba() untuk menghasilkan output probabilitas
10. Perhatikan bahwa hasil prediksi ada 2, dimana masing2 adalah nilai probabilitas untuk setiap class label. Ambil nilai probabilitas pasien phositive meninggal dalam waktu kurang dari 5 tahun. note : gunakan bantuan attirubte .classes_ untuk mengetahui urutan label dari hasil prediksi probabilitas.
11. Berapa nilai score roc_auc untuk data test?
12. Apakah model anda termasuk baik, overtting, atau underfitting?
13. Ulangi tahap di atas namun kali ini menggunakan algoritma DecisionTreeClassifier dan kalian bisa menggunakan RandomizedSearchCV apabila process training lama. pelajari algoritma DecisionTreeClassifier di linkberikut: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html?highlight=decisiontreeclassifier#sklearn.tree.DecisionTreeClassifier
14. Bandingkan scorenya dengan Algoritma KNN, mana yang lebih baik?

Note : Data Science adalah experiment, sangat di dimungkinkan memerlukan beberapa kali percobaan untuk mendapatkan hasil yang terbaik! Happy Coding :)

In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [ ]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [ ]:
# Code here
#import class algorithm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

#splitting data feature and data target
x = df.drop('survival_status', axis=1)
y = df['survival_status']

#Bagi kedua data menjadi data training dan data test dengan test_size=0.25.
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=21, stratify=y)

In [ ]:
print(x.shape, x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(306, 3) (229, 3) (77, 3) (229,) (77,)


In [ ]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
import numpy as np

#algoritma KNN sebagai model classifier
model = KNeighborsClassifier()
param_grid = {'n_neighbors':np.arange(5, 10), 'weights':['distance', 'uniform']}
gscv = GridSearchCV(model, param_grid=param_grid, scoring='roc_auc', cv=5)

#latih model thd data training
gscv.fit(x_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': array([5, 6, 7, 8, 9]),
                         'weights': ['distance', 'uniform']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='roc_auc', verbose=0)

In [ ]:
#hyperparameter terbaik untuk kombinasi hyperparameter
gscv.best_params_

{'n_neighbors': 9, 'weights': 'distance'}

In [ ]:
#score validasi terbaik 
gscv.best_score_

0.6963749485808309

In [ ]:
print(gscv.predict_proba(x_test))

[[0.76640791 0.23359209]
 [0.8102686  0.1897314 ]
 [0.66587193 0.33412807]
 [0.         1.        ]
 [0.63561764 0.36438236]
 [1.         0.        ]
 [0.56890607 0.43109393]
 [0.74925211 0.25074789]
 [0.86748364 0.13251636]
 [0.63561764 0.36438236]
 [0.08456511 0.91543489]
 [0.93701007 0.06298993]
 [0.74975557 0.25024443]
 [1.         0.        ]
 [0.85599152 0.14400848]
 [0.67505757 0.32494243]
 [0.86486004 0.13513996]
 [0.70977071 0.29022929]
 [1.         0.        ]
 [0.42283057 0.57716943]
 [0.58663027 0.41336973]
 [0.85599152 0.14400848]
 [1.         0.        ]
 [0.38560065 0.61439935]
 [0.93181605 0.06818395]
 [1.         0.        ]
 [0.67699442 0.32300558]
 [0.61450726 0.38549274]
 [0.49787749 0.50212251]
 [0.77022146 0.22977854]
 [1.         0.        ]
 [0.         1.        ]
 [0.70920083 0.29079917]
 [0.91620233 0.08379767]
 [0.25035954 0.74964046]
 [0.79728995 0.20271005]
 [0.88682464 0.11317536]
 [0.90426252 0.09573748]
 [0.51609136 0.48390864]
 [0.79950313 0.20049687]


In [ ]:
from sklearn.metrics import roc_auc_score

y_score = gscv.predict(x_test)
roc_auc_score(y_test, y_score)

0.5960526315789474

In [ ]:
probability_class_1 = gscv.predict_proba(x_test)[:, 0]
probability_class_1

array([0.76640791, 0.8102686 , 0.66587193, 0.        , 0.63561764,
       1.        , 0.56890607, 0.74925211, 0.86748364, 0.63561764,
       0.08456511, 0.93701007, 0.74975557, 1.        , 0.85599152,
       0.67505757, 0.86486004, 0.70977071, 1.        , 0.42283057,
       0.58663027, 0.85599152, 1.        , 0.38560065, 0.93181605,
       1.        , 0.67699442, 0.61450726, 0.49787749, 0.77022146,
       1.        , 0.        , 0.70920083, 0.91620233, 0.25035954,
       0.79728995, 0.88682464, 0.90426252, 0.51609136, 0.79950313,
       0.4663574 , 0.59621125, 0.74160185, 0.49059582, 0.87156043,
       1.        , 1.        , 0.91678933, 0.87330433, 0.10850447,
       0.74356248, 0.45351283, 0.56739356, 0.89604495, 0.54101941,
       1.        , 0.74533272, 0.55345835, 1.        , 0.10424717,
       0.55048243, 0.76955754, 0.79235698, 1.        , 0.76039498,
       0.81119487, 0.67281102, 0.89311194, 0.33567466, 1.        ,
       0.31216633, 0.76167484, 1.        , 0.12067642, 0.76025

In [ ]:
probability_class_2 = gscv.predict_proba(x_test)[:, 1]
probability_class_2

array([0.23359209, 0.1897314 , 0.33412807, 1.        , 0.36438236,
       0.        , 0.43109393, 0.25074789, 0.13251636, 0.36438236,
       0.91543489, 0.06298993, 0.25024443, 0.        , 0.14400848,
       0.32494243, 0.13513996, 0.29022929, 0.        , 0.57716943,
       0.41336973, 0.14400848, 0.        , 0.61439935, 0.06818395,
       0.        , 0.32300558, 0.38549274, 0.50212251, 0.22977854,
       0.        , 1.        , 0.29079917, 0.08379767, 0.74964046,
       0.20271005, 0.11317536, 0.09573748, 0.48390864, 0.20049687,
       0.5336426 , 0.40378875, 0.25839815, 0.50940418, 0.12843957,
       0.        , 0.        , 0.08321067, 0.12669567, 0.89149553,
       0.25643752, 0.54648717, 0.43260644, 0.10395505, 0.45898059,
       0.        , 0.25466728, 0.44654165, 0.        , 0.89575283,
       0.44951757, 0.23044246, 0.20764302, 0.        , 0.23960502,
       0.18880513, 0.32718898, 0.10688806, 0.66432534, 0.        ,
       0.68783367, 0.23832516, 0.        , 0.87932358, 0.23974

In [ ]:
x_test_new = x_test

x_test_new['Prob to survive < 5'] = probability_class_2
x_test_new.tail(5).reset_index(drop=True)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


Age  Patient's Years  N_positive_ax  Prob to survive < 5
0   66               58              0             0.000000
1   57               62             14             0.879324
2   76               67              0             0.239743
3   63               66              0             0.083699
4   62               65             19             0.634530